blueprint:
  source_url: https://github.com/Damian666/HomeAssistant/blob/2932abecbb73ddf09a47d1a3d8c759073b0b070f/blueprints/automation/Damian666/Lidl_4Button_Remote_Switch.yaml
  name: ZHA - Lidl 4 Button Remote Switch
  description: Automate your Lidl/LivarnoLux 4 Button Remote Switch using ZHA events.
  domain: automation

  input:
    Lidl_4Button_Remote:
      name: Lidl 4Button Remote
      description: Select the Lidl 4 Button Remote to use
      selector:
        device:
          integration: zha
          manufacturer: _TYZB01_bngwdjsr
          model: TS1001
          multiple: false
    button_one_short_press:
      name: Single Press
      description: Action to run on button 1 (OFF/0) single press
      default: []
      selector:
        action: {}
    button_two_short_press:
      name: Single Press
      description: Action to run on button 2 (ON/1) single press
      default: []
      selector:
        action: {}
    button_three_short_press:
      name: Single Press
      description: Action to run on button 3 (Bright) single press
      default: []
      selector:
        action: {}
    button_four_short_press:
      name: Single Press
      description: Action to run on button 4 (Dim) single press
      default: []
      selector:
        action: {}
mode: restart
max_exceeded: silent
trigger:
- platform: event
  event_type: zha_event
  event_data:
    device_id: !input 'Lidl_4Button_Remote'
action:
- variables:
    command: '{{ trigger.event.data.command }}'
    args: '{{ trigger.event.data.args }}'
    stepmode: '{{trigger.event.data.params.step_mode}}'
- choose:
  - conditions: '{{ command == ''off'' }}'
    sequence: !input 'button_one_short_press'
  - conditions: '{{ command == ''on'' }}'
    sequence: !input 'button_two_short_press'
  - conditions: '{{  command == ''step'' and stepmode == ''StepMode.Up'' }}'
    sequence: !input 'button_three_short_press'
  - conditions: '{{  command == ''step'' and stepmode == ''StepMode.Down'' }}'
    sequence: !input 'button_four_short_press'