blueprint:
  source_url: https://github.com/Damian666/HomeAssistant/blob/c4f35fd48fea5833e0ffadb56767cfe6528f0010/blueprints/automation/Damian666/Lidl_4Button_Remote_Switch.yaml
  name: ZHA - Lidl 4Button Remote Switch
  description: Automate your Lidl/LivarnoLux 4Button Remote Switch using ZHA events.
  domain: automation
  input:
    Lidl_4Button_Remote_switch:
      name: Lidl 4Button Remote Switch
      description: Select the Lidl 4Button Remote Switch to use
      selector:
        device:
          integration: zha
          manufacturer: _TYZB01_bngwdjsr
          model: TS1001
    button_one_short_press:
      name: Single Press
      description: Action to run on button 1 single press
      default: []
      selector:
        action: {}
    button_two_short_press:
      name: Single Press
      description: Action to run on button 2 single press
      default: []
      selector:
        action: {}
    button_three_short_press:
      name: Single Press
      description: Action to run on button 3 single press
      default: []
      selector:
        action: {}
    button_three_long_press:
      name: Long Press
      description: Action to run on button 3 long press
      default: []
      selector:
        action: {}
    button_four_short_press:
      name: Single Press
      description: Action to run on button 4 single press
      default: []
      selector:
        action: {}  
    button_four_long_press:
      name: Long Press
      description: Action to run on button 4 long press
      default: []
      selector:
        action: {}
mode: restart
max_exceeded: silent
trigger:
- platform: event
  event_type: zha_event
  event_data:
    device_id: !input 'Lidl_4Button_Remote_switch'
action:
- variables:
    command: '{{ trigger.event.data.command }}'
    args: '{{ trigger.event.data.args }}'
- choose:
  - conditions: '{{ command == ''off'' }}'
    sequence: !input 'button_one_short_press'
  - conditions: '{{ command == ''on'' }}'
    sequence: !input 'button_two_short_press'
  - conditions: '{{  command == ''step'' and args == [0,51,10] }}'
    sequence: !input 'button_three_short_press'
  - conditions: '{{  command == ''step'' and args == [1,51,10] }}'
    sequence: !input 'button_four_short_press'
  - conditions: '{{ command == "move" and args == [0, 51,] }}'
    sequence: !input 'button_three_long_press'
  - conditions: '{{ command == "move" and args == [1, 51,] }}'
    sequence: !input 'button_four_long_press'
